# Gmsh - Copyright (C) 1997-2020 C. Geuzaine, J.-F. Remacle
#
# See the LICENSE.txt file for license information. Please report all
# issues on https://gitlab.onelab.info/gmsh/gmsh/issues.

variables:
  EXTRA_OPTION: ""

.ssh_config: &ssh_config
  before_script:
    - echo "$SSH_TOKEN" > ~/.ssh/id_rsa
    - echo "Host *" > ~/.ssh/config
    - echo "StrictHostKeyChecking no" >> ~/.ssh/config
    - chmod 700 ~/.ssh/id_rsa ~/.ssh/config

.linux_official: &linux_official
  <<: *ssh_config
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DGMSH_HOST=gmsh.info ${EXTRA_OPTION} ..
    - make package -j 8
    - PKG=`ls gmsh-*.tar*`
    - scp ${PKG} geuzaine@gmsh.info:.wwwgmsh/bin/Linux/${PKG/\.tar\.gz/\.tgz}
    - ctest -j 8 --output-on-failure
  tags:
    - linux64
    - docker

linux64_official_snapshot:
  image: onelab/debian.wheezy.64bit
  variables:
    EXTRA_OPTION: "-DBLAS_LAPACK_LIBRARIES='/usr/local/lib/libopenblas.a;/usr/local/lib64/libgfortran.a;/usr/local/lib64/libquadmath.a;-lpthread;-static-libstdc++'"
  <<: *linux_official
  except:
    - tags
